#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# YAML validated using http://www.yamllint.com/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: false

env:
  global:
    - _R_CHECK_FULL_=true  ## Package specific

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
      env:
        - R_KEEP_PKG_SOURCE=yes
        - _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=true
        - _R_S3_METHOD_LOOKUP_USE_TOPENV_AS_DEFENV_=true
        - _R_CHECK_CONNECTIONS_LEFT_OPEN_=true
        - _R_CHECK_LENGTH_1_CONDITION_=true
        - _R_CHECK_LENGTH_1_LOGIC2_=true
        - _R_CLASS_MATRIX_ARRAY_=true
    - os: linux
      r: devel
      r_github_packages:
      - mllg/batchtools
      env:
        - NB='w/ batchtools devel'  ## Just a label
    - os: osx
      r: oldrel
    - os: osx
      r: release
    - os: linux
      r: release
      r_github_packages:
        - HenrikBengtsson/future.tests
      script:
        - R CMD build --no-build-vignettes --no-manual .
        - R CMD INSTALL *.tar.gz
      after_success:
        - Rscript -e future.tests::check --args --test-plan=future.batchtools::batchtools_local
      env: NB='w/ future.tests' ## Just a label
    - os: linux
      r: release
      r_packages:
        - covr
      script:
        - R CMD build --no-build-vignettes --no-manual .
      after_success:
        - Rscript -e 'covr::codecov(quiet=FALSE)'
      env: NB='w/ covr' ## Just a label

before_install:
  - Rscript -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'

notifications:
  email:
    on_success: change
    on_failure: change
